create database practicals;

use practicals;
Create table EMP_INFO(
W_ID int NOT NULL PRIMARY KEY,
F_NAME varchar(50),
L_NAME varchar(50),
JOIN_DATE date,
DOB date,
GENDER int NOT NULL,
DEPARTMENT_ID int
);

CREATE TABLE DEPT_INFO(
DEPARTMENT_ID int primary key,
DEPARTMENT_NAME VARCHAR(30)
);

CREATE TABLE EMP(
W_ID int primary key,
EMP_POSITION VARCHAR(30),
SAL int
);

ALTER TABLE EMP_INFO 
add constraint W_ID
foreign key (W_ID) 
references EMP (W_ID);

ALTER TABLE EMP_INFO 
add constraint DEPARTMENT_ID
foreign key (DEPARTMENT_ID) 
references DEPT_INFO (DEPARTMENT_ID);

ALTER TABLE EMP_INFO RENAME COLUMN F_NAME to EMPLOYEE_NAME;

SELECT EMPLOYEE_NAME FROM EMP_INFO union select L_NAME FROM EMP_INFO;
ALTER TABLE EMP_INFO RENAME COLUMN EMPLOYEE_NAME TO FullName;


INSERT INTO DEPT_INFO VALUES (001,'HR'),(002,'BCA'),(003,'MCA'),(004,'BCA'),(005,'MCA'),(006,'HR'),(007,'HR');
SELECT DEPARTMENT_NAME FROM DEPT_INFO WHERE DEPARTMENT_NAME='HR' ;

INSERT INTO EMP VALUES (001,'lead',10000),(002,'head',30000),(003,'manager',25000),(004,'watchman',15000),(005,'HR',10560),
(006,'lead',14000),(007,'manager',10900);
select *from EMP WHERE SAL>10000 AND SAL<20000;